apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: exam
spec:
  selector:
    app: frontend
  ports:
    - port: 80          # The port exposed by the service
      targetPort: 80     # The port on the frontend pods that the service forwards traffic to
      nodePort: 30080
  type: NodePort